## Numpy Arrays
Arrays are special multiple dimensional data structures that allow for efficient computation and manipulation. You can think of them as nested lists but can only one type of data. Numpy arrays are very similar to Matlab arrays and allow for some level of cross-capability between the two languages. 

In [1]:
import numpy as np

Making an array

In [4]:
x1 = np.array([2,1,2,2])
print(x1)

x2 = np.array([2,1,2,'a'])
print(x2)

[2 1 2 2]
['2' '1' '2' 'a']


This 1-dimensional array works similar to a list. We can subset an array using an index

In [7]:
# selects the first element 
print(x[0])

# selects the last element
print(x[-1])

# selects a subset
print(x[2:4])

2
2
[2 2]


3 dimensional arrays (closer to real world data structures) have an extra dimension. To make them, we can use a nested list with one list for each row or use the shape on a 1-dimensional array

In [8]:
x_3d = np.array([[2,3,4], [2,1,3]])
print(x_3d)

[[2 3 4]
 [2 1 3]]


In [11]:
x_3d = np.array([2,3,4,2,1,3])
x_3d.shape = (2,3) # 2 rows and 3 columns
print(x_3d)

[[2 3]
 [4 2]
 [1 3]]


In [14]:
np.array([2,3,4,5,65,6])

array([ 2,  3,  4,  5, 65,  6])